### ISSUE TITLE
No Ping - Error

### ISSUE THREAD

**Issue by Muhammad-Bo** [dhanyaramesh06/shortest-path-sdn#1]
Hello,
During the Run of the Repo, When trying to ping h2 from h1, the controller faces with following error:

```
get_path is called, src= 1  dst= 11  first_port= 2  final_port= 2
Q= set([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])
ProjectController: Exception occurred during handler processing. Backtrace from offending handler [_packet_in_handler] servicing event [EventOFPPacketIn] follows.
Traceback (most recent call last):
  File "/home/osboxes/.local/lib/python2.7/site-packages/ryu/base/app_manager.py", line 290, in _event_loop
    handler(ev)
  File "/home/osboxes/Desktop/Netlab_ryu/dij2/RYU_Controller_spr.py", line 152, in _packet_in_handler
    p = get_path(mymac[src][0], mymac[dst][0], mymac[src][1], mymac[dst][1])
  File "/home/osboxes/Desktop/Netlab_ryu/dij2/RYU_Controller_spr.py", line 47, in get_path
    Q.remove(u)
KeyError: 0
```
Thank You

**Comment by aidakrr** [comment]
i got same error too, how to resolve this?
